using AiAlreadyDidIt.Api.Entities;
using AiAlreadyDidIt.Api.Services.Search;

namespace AiAlreadyDidIt.Tests;

public class EmbeddingTextTests
{
    [Fact]
    public void App_text_joins_name_descriptions_tags_category_model_and_readme()
    {
        var app = new App
        {
            Name = "HWMonitor for Linux",
            ShortDescription = "Sensor dashboard",
            LongDescription = "Shows temperatures and fan speeds.",
            TagsText = "sensors, gtk, python",
            CategoryPathText = "System & Utilities › Hardware & Sensors",
            LlmModel = new LlmModel { Vendor = "Anthropic", Name = "Claude Fable", Version = "5.1" },
            ReadmeMarkdown = "# HWMonitor\n\n![s](a.png) Reads **lm-sensors** output."
        };
        var text = EmbeddingService.BuildAppText(app);
        var lines = text.Split('\n');
        Assert.Equal("HWMonitor for Linux", lines[0]);
        Assert.Equal("Sensor dashboard", lines[1]);
        Assert.Equal("Shows temperatures and fan speeds.", lines[2]);
        Assert.Contains("Tags: sensors, gtk, python", lines);
        Assert.Contains("Category: System & Utilities › Hardware & Sensors", lines);
        Assert.Contains("Generated by Anthropic Claude Fable 5.1", lines);
        Assert.Contains("HWMonitor Reads lm-sensors output.", lines[^1]);
        Assert.DoesNotContain("![", text);
    }

    [Fact]
    public void Explicit_category_path_overrides_the_stored_one()
    {
        var app = new App { Name = "x", ShortDescription = "y", LongDescription = "z", CategoryPathText = "Old" };
        Assert.Contains("Category: New › Path", EmbeddingService.BuildAppText(app, "New › Path"));
        Assert.DoesNotContain("Old", EmbeddingService.BuildAppText(app, "New › Path"));
    }

    [Fact]
    public void Long_description_and_readme_are_capped()
    {
        var app = new App { Name = "n", ShortDescription = "s", LongDescription = new string('d', 10_000), ReadmeMarkdown = new string('r', 10_000) };
        var text = EmbeddingService.BuildAppText(app);
        Assert.True(text.Length < 8_000);
        Assert.Contains(new string('d', 3000), text);
        Assert.DoesNotContain(new string('d', 3001), text);
    }

    [Fact]
    public void Draft_text_skips_empty_parts()
    {
        Assert.Equal("Name\nShort", EmbeddingService.BuildDraftText("Name", "Short", null, "  "));
        Assert.Equal("Name\nTags: a, b", EmbeddingService.BuildDraftText("Name", "", null, "a, b"));
        Assert.Equal(string.Empty, EmbeddingService.BuildDraftText(null, null, null));
    }
}
