using System.Net;
using System.Text;
using System.Text.Json;
using AiAlreadyDidIt.Api.Data;
using AiAlreadyDidIt.Api.Data.Seed;
using AiAlreadyDidIt.Api.Entities;
using AiAlreadyDidIt.Api.Infrastructure;
using AiAlreadyDidIt.Api.Services.Agent;
using AiAlreadyDidIt.Api.Services.Catalog;
using Markdig;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace AiAlreadyDidIt.Api.Controllers.V1.Seo;

/// <summary>
/// Server-rendered HTML for crawlers and link previews (nginx routes bot user-agents on /app/* here), plus sitemap,
/// robots and llms.txt. Humans get the SPA.
/// </summary>
[ApiController]
[AllowAnonymous]
public class SeoController(AadiDbContext db, CatalogService catalog, AgentService agent, SiteSettingsCache settings, IOptions<SiteOptions> site) : ControllerBase
{
    private static readonly MarkdownPipeline Markdown = new MarkdownPipelineBuilder().UseAdvancedExtensions().DisableHtml().Build();
    private string PublicUrl => site.Value.PublicUrl.TrimEnd('/');

    [HttpGet("seo/app/{slug}")]
    [Produces("text/html")]
    public async Task<IActionResult> App(string slug, CancellationToken ct)
    {
        var app = await db.Apps.AsNoTracking().Include(a => a.Category).Include(a => a.License).Include(a => a.LlmModel).Include(a => a.Uploader)
            .Include(a => a.Screenshots).Include(a => a.Prompts).Include(a => a.AppTags).ThenInclude(t => t.Tag)
            .Include(a => a.Versions).ThenInclude(v => v.Files).ThenInclude(f => f.Platform)
            .FirstOrDefaultAsync(a => a.Slug == slug && a.Status == AppStatus.Published, ct);
        if (app is null) return NotFound();
        var d = await catalog.MapDetailAsync(app, false, ct);
        var title = $"{d.Name} — free open-source app generated by {d.LlmModel?.DisplayName ?? "an LLM"} | {site.Value.Name}";
        var description = TextUtil.Truncate(d.ShortDescription, 160);
        var canonical = $"{PublicUrl}/app/{d.Slug}";
        var image = d.Screenshots.FirstOrDefault()?.Url is { } img ? PublicUrl + img : null;
        var jsonLd = JsonSerializer.Serialize(new Dictionary<string, object?>
        {
            ["@context"] = "https://schema.org",
            ["@type"] = "SoftwareApplication",
            ["name"] = d.Name,
            ["description"] = d.ShortDescription,
            ["url"] = canonical,
            ["applicationCategory"] = d.CategoryPath.LastOrDefault()?.NameEn,
            ["operatingSystem"] = string.Join(", ", d.Platforms),
            ["softwareVersion"] = d.LatestVersion?.Version,
            ["license"] = d.License.Url,
            ["isAccessibleForFree"] = true,
            ["offers"] = new { @type = "Offer", price = "0", priceCurrency = "USD" },
            ["image"] = image,
            ["author"] = new { @type = "Person", name = d.Uploader.DisplayName, url = $"{PublicUrl}/u/{d.Uploader.Username}" },
            ["aggregateRating"] = d.RatingCount > 0 ? new { @type = "AggregateRating", ratingValue = d.RatingAvg, bestRating = 100, worstRating = 0, ratingCount = d.RatingCount } : null,
            ["downloadUrl"] = canonical,
            ["dateModified"] = d.UpdatedAt.ToString("O"),
            ["datePublished"] = d.PublishedAt?.ToString("O")
        }, new JsonSerializerOptions { DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull });

        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append($"<title>{E(title)}</title><meta name=\"description\" content=\"{E(description)}\"><link rel=\"canonical\" href=\"{canonical}\">");
        sb.Append($"<meta property=\"og:type\" content=\"website\"><meta property=\"og:title\" content=\"{E(d.Name)}\"><meta property=\"og:description\" content=\"{E(description)}\"><meta property=\"og:url\" content=\"{canonical}\"><meta property=\"og:site_name\" content=\"{E(site.Value.Name)}\">");
        if (image is not null) sb.Append($"<meta property=\"og:image\" content=\"{image}\"><meta name=\"twitter:card\" content=\"summary_large_image\"><meta name=\"twitter:image\" content=\"{image}\">");
        sb.Append($"<script type=\"application/ld+json\">{jsonLd}</script>");
        sb.Append("<style>body{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#222}img{max-width:100%;height:auto}pre{white-space:pre-wrap;background:#f5f5f5;padding:1rem}table{border-collapse:collapse}td,th{border:1px solid #ddd;padding:.4rem .6rem}</style></head><body>");
        sb.Append($"<p><a href=\"{PublicUrl}\">{E(site.Value.Name)}</a> › ");
        sb.Append(string.Join(" › ", d.CategoryPath.Select(c => $"<a href=\"{PublicUrl}/category/{c.Slug}\">{E(c.NameEn)}</a>")));
        sb.Append("</p>");
        sb.Append($"<h1>{E(d.Name)}</h1><p><strong>{E(d.ShortDescription)}</strong></p>");
        sb.Append("<table><tr><th>License</th><td>" + E(d.License.SpdxId) + "</td></tr>");
        sb.Append("<tr><th>Generated by</th><td>" + E(d.LlmModel?.DisplayName ?? "unknown") + (d.LlmModelNote is null ? "" : " — " + E(d.LlmModelNote)) + "</td></tr>");
        sb.Append("<tr><th>Platforms</th><td>" + E(string.Join(", ", d.Platforms)) + "</td></tr>");
        sb.Append($"<tr><th>Rating</th><td>{d.RatingAvg:0}/100 ({d.RatingCount} ratings) · worked for {d.WorkedCount}, didn't for {d.NotWorkedCount}</td></tr>");
        sb.Append($"<tr><th>Downloads</th><td>{d.DownloadCount}</td></tr>");
        sb.Append($"<tr><th>Latest version</th><td>{E(d.LatestVersion?.Version ?? "-")} ({d.LatestVersion?.ReleasedAt:yyyy-MM-dd})</td></tr>");
        if (d.RepoUrl is not null) sb.Append($"<tr><th>Source</th><td><a href=\"{E(d.RepoUrl)}\" rel=\"nofollow\">{E(d.RepoUrl)}</a></td></tr>");
        sb.Append($"<tr><th>Uploader</th><td><a href=\"{PublicUrl}/u/{d.Uploader.Username}\">{E(d.Uploader.DisplayName)}</a></td></tr>");
        sb.Append($"<tr><th>Estimated generation cost</th><td>{d.EstGenerationTokens:N0} tokens (≈ ${d.EstGenerationCostUsd:N2}) — saved so far: {d.EstSavedTokens:N0} tokens</td></tr></table>");
        if (d.Screenshots.Count > 0)
        {
            sb.Append("<h2>Screenshots</h2>");
            foreach (var s in d.Screenshots) sb.Append($"<p><img src=\"{PublicUrl}{s.Url}\" alt=\"{E(s.Caption ?? d.Name + " screenshot")}\" width=\"{s.Width}\" height=\"{s.Height}\" loading=\"lazy\"></p>");
        }
        sb.Append("<h2>Description</h2>").Append(Markdig.Markdown.ToHtml(d.LongDescription, Markdown));
        if (d.LatestVersion is not null)
        {
            sb.Append("<h2>Downloads</h2><ul>");
            foreach (var f in d.LatestVersion.Files)
                sb.Append($"<li><a href=\"{site.Value.ApiPublicUrl.TrimEnd('/')}{f.DownloadUrl}?source=seo\" rel=\"nofollow\">{E(f.FileName)}</a> — {E(f.PlatformName ?? f.Kind.ToString())}{(f.SizeBytes > 0 ? ", " + TextUtil.HumanSize(f.SizeBytes) : "")}</li>");
            sb.Append("</ul>");
            if (!string.IsNullOrWhiteSpace(d.LatestVersion.Changelog)) sb.Append("<h3>What's new</h3>").Append(Markdig.Markdown.ToHtml(d.LatestVersion.Changelog, Markdown));
        }
        if (d.Prompts.Count > 0)
        {
            sb.Append("<h2>Original prompt(s)</h2>");
            foreach (var p in d.Prompts) sb.Append($"<h3>{E(p.Title)}</h3><pre>{E(p.PromptText)}</pre>");
        }
        if (d.Tags.Count > 0) sb.Append("<p>Tags: " + string.Join(", ", d.Tags.Select(t => $"<a href=\"{PublicUrl}/search?tags={WebUtility.UrlEncode(t)}\">{E(t)}</a>")) + "</p>");
        sb.Append($"<p><a href=\"{canonical}\">Open in {E(site.Value.Name)}</a></p></body></html>");
        return Content(sb.ToString(), "text/html; charset=utf-8");
    }

    [HttpGet("sitemap.xml")]
    [Produces("application/xml")]
    public async Task<IActionResult> Sitemap(CancellationToken ct)
    {
        var apps = await db.Apps.AsNoTracking().Where(a => a.Status == AppStatus.Published).OrderByDescending(a => a.UpdatedAt).Select(a => new { a.Slug, a.UpdatedAt }).Take(50000).ToListAsync(ct);
        var categories = await db.Categories.AsNoTracking().Where(c => c.IsActive && !c.IsLlmProposed).Select(c => c.Slug).ToListAsync(ct);
        var sb = new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">");
        sb.Append($"<url><loc>{PublicUrl}/</loc><changefreq>hourly</changefreq><priority>1.0</priority></url>");
        foreach (var page in new[] { "search", "wanted", "about", "for-agents" }) sb.Append($"<url><loc>{PublicUrl}/{page}</loc><changefreq>daily</changefreq></url>");
        foreach (var c in categories) sb.Append($"<url><loc>{PublicUrl}/category/{c}</loc><changefreq>daily</changefreq><priority>0.6</priority></url>");
        foreach (var a in apps) sb.Append($"<url><loc>{PublicUrl}/app/{a.Slug}</loc><lastmod>{a.UpdatedAt:yyyy-MM-dd}</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>");
        sb.Append("</urlset>");
        return Content(sb.ToString(), "application/xml; charset=utf-8");
    }

    [HttpGet("robots.txt")]
    public IActionResult Robots() => Content($"User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /dashboard\nDisallow: /api/v1/my\nSitemap: {PublicUrl}/sitemap.xml\n", "text/plain; charset=utf-8");

    /// <summary>llms.txt — a plain-text guide for language models (https://llmstxt.org).</summary>
    [HttpGet("llms.txt")]
    public async Task<IActionResult> LlmsTxt(CancellationToken ct)
    {
        var docs = await agent.DocsAsync(ct);
        var sb = new StringBuilder();
        sb.AppendLine($"# {docs.Name}").AppendLine().AppendLine($"> {docs.Mission}").AppendLine();
        sb.AppendLine("## Before you generate an application").AppendLine().AppendLine(docs.Flow).AppendLine();
        sb.AppendLine("## Endpoints").AppendLine();
        foreach (var (k, v) in docs.Endpoints) sb.AppendLine($"- {k}: {v}");
        sb.AppendLine().AppendLine($"- OpenAPI: {docs.OpenApiUrl}").AppendLine($"- MCP server (Streamable HTTP): {docs.McpUrl} — tools: check_before_building, search_apps, get_app, list_categories, download_app, submit_app_request");
        sb.AppendLine().AppendLine("## Authentication").AppendLine().AppendLine(docs.Authentication).AppendLine().AppendLine("## Rate limits").AppendLine().AppendLine(docs.RateLimits);
        sb.AppendLine().AppendLine($"Published apps right now: {docs.PublishedApps}. Default description: {await settings.GetStringAsync(SettingKeys.SeoDefaultDescription, "", ct)}");
        return Content(sb.ToString(), "text/plain; charset=utf-8");
    }

    private static string E(string? s) => WebUtility.HtmlEncode(s ?? string.Empty);
}
