using AiAlreadyDidIt.Api.Entities;
using AiAlreadyDidIt.Api.Infrastructure;
using AiAlreadyDidIt.Api.Infrastructure.Ai;
using Pgvector;

namespace AiAlreadyDidIt.Api.Services.Search;

/// <summary>Builds the text that represents an app and turns it into a pgvector <see cref="Vector"/>.</summary>
public sealed class EmbeddingService(ILlmProviderFactory providers, ILogger<EmbeddingService> logger)
{
    public bool Available => providers.Embeddings.SupportsEmbeddings;
    public string ModelName => $"{providers.Embeddings.Name}:{providers.Embeddings.EmbeddingModel}";

    /// <summary>name | short | long | tags | category | README excerpt — capped so every model's context is respected.</summary>
    public static string BuildAppText(App app, string? categoryPath = null)
    {
        var parts = new List<string>
        {
            app.Name,
            app.ShortDescription,
            TextUtil.Truncate(app.LongDescription, 3000)
        };
        if (!string.IsNullOrWhiteSpace(app.TagsText)) parts.Add("Tags: " + app.TagsText);
        var cat = categoryPath ?? app.CategoryPathText;
        if (!string.IsNullOrWhiteSpace(cat)) parts.Add("Category: " + cat);
        if (app.LlmModel is not null) parts.Add("Generated by " + app.LlmModel.DisplayName);
        if (!string.IsNullOrWhiteSpace(app.ReadmeMarkdown)) parts.Add(TextUtil.Truncate(TextUtil.Excerpt(app.ReadmeMarkdown, 4000), 4000));
        return string.Join("\n", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    public static string BuildDraftText(string? name, string? shortDescription, string? longDescription, string? tags = null)
    {
        var parts = new[] { name, shortDescription, TextUtil.Truncate(longDescription, 3000), string.IsNullOrWhiteSpace(tags) ? null : "Tags: " + tags };
        return string.Join("\n", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    public async Task<Vector?> TryEmbedAsync(string text, CancellationToken ct)
    {
        if (!Available || string.IsNullOrWhiteSpace(text)) return null;
        try
        {
            var floats = await providers.Embeddings.EmbedAsync(text, ct);
            if (floats.Length != providers.EmbeddingDimensions)
                throw new InvalidOperationException($"Embedding width {floats.Length} does not match Ai:EmbeddingDimensions={providers.EmbeddingDimensions}.");
            return new Vector(floats);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            logger.LogWarning(ex, "Embedding failed; falling back to keyword-only");
            return null;
        }
    }

    public async Task<Vector> EmbedAsync(string text, CancellationToken ct)
    {
        var floats = await providers.Embeddings.EmbedAsync(text, ct);
        if (floats.Length != providers.EmbeddingDimensions)
            throw new InvalidOperationException($"Embedding width {floats.Length} does not match Ai:EmbeddingDimensions={providers.EmbeddingDimensions}.");
        return new Vector(floats);
    }
}
